### ISSUE TITLE
My code ran out of strange results：RMSE:164, Score:37860992784

### ISSUE THREAD

**Issue by 943fansi** [mohyunho/ENAS-PdM#3]
[result.png](https://obohe.com/i/2021/11/17/ozrr5m.png)

**Comment by mohyunho** [comment]
I cannot access to the png file attached. I ran this code for two different HW to check the reliability. If those results are the prediction performance of an optimized architecture discovered my EA, please share me your repo. (for sure if you do not mind), then i could check the details.

**Comment by 943fansi** [comment]
result(png) and main code (code_to.py)  
https://github.com/943fansi/damn_search
Unable to upload preprocessed data file due to file size limitation.Since I'm in China, I don't know whether you use China's online disk. It seems difficult to share data files. Could you provide me some suggestions?
As for data used in my code,
They are 4 groups, each containing 4. npy (ndarray saved by numpy). After similar operations, set MAX RUL=130, normalized and divided by two sliding windows, seq_ len=30, win_ size=3.

**Comment by 943fansi** [comment]
now it has data file in .zip file,the same address above.

**Comment by mohyunho** [comment]
Sorry for my late response. I just get back from my long vacation. Because we have discussed it rather long time ago, i am not sure you have addressed this issue or not.  If you still has the problem, please let me know.

**Comment by 943fansi** [comment]
very nice to meet you again! how is your holiday? I've solved that problem.

**Comment by mohyunho** [comment]
It was nice. Thank you. The implemented codes in this repository are very early version of my works. Those have never been cleaned up and i hardly put comments on them. I am so sorry for that. A new repository relevant to this work will be publicly available soon. I will share it and let you know when it is published.

**Comment by 943fansi** [comment]
> 很好。谢谢。这个存储库中实现的代码是我作品的早期版本。这些从未被清理过，我几乎不对它们发表评论。我很抱歉。与这项工作相关的新存储库将很快公开发布。我会分享它，并在发布时通知您。

Thank you.
